name: Deploy AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Only for Python Lambdas with requirements.txt
      - name: Install dependencies
        if: hashFiles('requirements.txt') != ''
        run: |
          pip install -r requirements.txt -t ./src
          
      - name: Package Lambda code
        run: |
          cd src
          zip -r ../lambda_function.zip . -x "*.git*"
          cd ..

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name my-lambda-func \
            --zip-file fileb://lambda_function.zip
